version: '3.4'

networks:
   frontend:
   backend:

services:

   mssqlserver:
      image: "microsoft/mssql-server-linux:latest"
      ports:
         - "1445:1433"
      container_name: shoesmssqllinux
      environment:
         - ACCEPT_EULA=Y
         - SA_PASSWORD=ProductApi@
      networks:
         - backend

   catalogapi:
      image: ${DOCKER_REGISTRY-}catalogapi
      build:
         context: .
         dockerfile: src/Services/ProductCatalogApi/Dockerfile
      environment:
         - DatabaseServer=192.168.99.100
         - DataBasePort=1445 
         - DatabaseName=CatalogDb
         - DatabaseUser=sa
         - DatabasePassword=ProductApi@
      container_name: catalogapi
      ports:
         - "5000:80"
      networks:
         - backend
         - frontend
      depends_on:
         - mssqlserver   

